engines:
  coffeelint:
    enabled: true
ratings:
   paths:
   - client/**/*.coffee
   - server/**/*.coffee
exclude_paths:
  - "tests/jasmine/server/unit/packageMocksSpec.js"
  - "tests/jasmine/server/unit/package-stubs.js"
  - "tests/client/e2e/protractor.config.js"
