language: node_js
node_js:
  - "0.10"
sudo: required
script:
  - meteor run --test
  - "cd .gulp && gulp test:unit"
before_script:
  - cd .gulp
  - npm install
  - npm install -g codeclimate-test-reporter
  - gulp build
  - cd ../
  - curl https://install.meteor.com/ | sh
after_script:
  - "cd ../ && codeclimate < tests/coverage/phantomjs/lcov.info"
addons:
  code_climate:
    repo_token: 6ca72ca29fad172c4217d0f11b5254e433ac548258b4508c20b7db49b1e09d14
services:
  - mongodb
notifications:
  email: false
