language: node_js
node_js:
  - "0.10"
script:
  - meteor run --test
  - .gulp/gulp test:unit
before_script:
  - cd .gulp
  - npm install
  # - npm install -g codeclimate-test-reporter
  - gulp build
  - cd ../
# after_script:
#   - codeclimate < coverage/phantomjs/lcov.info
# addons:
#   code_climate:
#     repo_token: 9bc93c16ae561b78e7f3933e6c0d25be1ea60cff3e101df657f70ded923a1333
notifications:
  email: false
